services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
